config/routes.rb
Boardgames::Application.routes.draw do

  root 'sessions#new'

  get 'register', to: 'users#new'
  post 'register', to: 'users#create'
  get 'signin', to: 'sessions#new'
  get 'signout', to: 'sessions#destroy'

  resources :board_games
  resources :game_plays
  resources :players
  resources :sessions, only: [:new, :create, :destroy]

end

app/models/board_game.rb
class BoardGame < ActiveRecord::Base
	belongs_to :user
	has_and_belongs_to_many :game_plays

	validates :name, presence: true, uniqueness: { case_sensitive: false, scope: :user }
	validates :rounds, if: :round_based?, numericality: { only_integer: true, greater_than: 0 }
end

app/models/game_play.rb
class GamePlay < ActiveRecord::Base
	belongs_to :user
	has_and_belongs_to_many :board_games
	has_and_belongs_to_many :players

	def board_game
		if self.board_games.any?
			self.board_games.first
		else
			nil
		end
	end

	def board_game=(board_game)
		if self.board_games.any?
			self.board_games.delete_all
		end
		
		self.board_games.push board_game
	end

	def date_string
		self.created_at.localtime.strftime("%-m/%d/%y")
	end

	def players_string
		if self.players.any?
			self.players.sort_by { |p| p.name }.collect { |p| p.name }.join(", ")
		else
			"Solo play"
		end
	end

	def player_count_string
		"Players: #{self.players.count + 1}"
	end
end

app/models/player.rb
class Player < ActiveRecord::Base
	belongs_to :user
	has_and_belongs_to_many :game_plays

	validates :name, presence: true, length: { maximum: 50 },
	 uniqueness: { case_sensitive: false}
end

app/models/user.rb
class User < ActiveRecord::Base
  	has_many :board_games
  	has_many :game_plays
  	has_many :players

	before_save { self.email = email.downcase }
	before_create :create_remember_token

 	validates :name, presence: true, length: { maximum: 50 }
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  	validates :email, presence: true, format: { with: VALID_EMAIL_REGEX },
  		uniqueness: { case_sensitive: false }
	has_secure_password
	validates :password, length: { minimum: 6 }

	def User.new_remember_token
		SecureRandom.urlsafe_base64
	end

	def User.encrypt(token)
		Digest::SHA1.hexdigest(token.to_s)
	end

	private

		def create_remember_token
			self.remember_token = User.encrypt(User.new_remember_token)
		end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/board_games_controller.rb
class BoardGamesController < ApplicationController
	before_action :signed_in_user
	before_action :correct_user, only: [:edit, :update, :show]

	def index
		@board_games = current_user.board_games.sort_by { |boardgame| boardgame.name }

		respond_to do |format| 
			format.html
			format.json { render json: @board_games }
		end
	end

	def new
		@board_game = BoardGame.new
	end

	def create
		@board_game = current_user.board_games.new(board_game_params)

		@board_game.save

		redirect_to board_games_path
	end

	def edit
		@board_game = BoardGame.find(params[:id])
	end

	def show
		@board_game = BoardGame.find(params[:id])
	end

	def update
		@board_game = BoardGame.find(params[:id])
		if @board_game.update_attributes(board_game_params)
			flash[:success] = "Board game updated"
			redirect_to board_game_path(@board_game.id)
		else
			render 'edit'
		end
	end

	private

		def board_game_params
			params.require(:board_game).permit(:name, :image_url, :description,
				:rule_book_link, :starting_player_rule, :round_based, :rounds)
		end

		def correct_user
			if !current_user.board_games.include?(BoardGame.find(params[:id]))
				redirect_to board_games_path
			end
		end
end

app/controllers/game_plays_controller.rb
class GamePlaysController < ApplicationController
	before_action :signed_in_user

	def index
		@game_plays = current_user.game_plays.reverse
	end

	def edit
	end

	def new
		@game_play = GamePlay.new
		@board_games = current_user.board_games.sort_by { |b| b.name }
		@players = current_user.players.sort_by { |n| n.name }
	end

	def update
	end

	def show
		@game_play = GamePlay.find(params[:id])
	end

	def create
		@game_play = current_user.game_plays.build()
		@game_play.board_game = BoardGame.find_by_id(params[:board_game_id])

		player_ids = params[:game_play][:player_ids].select { |p| !p.empty? }

		player_ids.each do |p|
			player = Player.find_by_id(p)
			@game_play.players << player
		end
		
		if @game_play.save
			redirect_to game_plays_path
		else
			render 'new'
		end
	end

	def destroy
		GamePlay.destroy(params[:id])
		redirect_to game_plays_path
	end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
	before_action :signed_in_user

	def new
		@player = Player.new
	end

	def create
		@player = current_user.players.build(player_params)
		if @player.save
			redirect_to players_path
		else
			render 'new'
		end
	end

	def index
		@players = current_user.players.sort_by { |p| p.name }
	end

	def show
		@player = Player.find_by_id(params[:id])
	end

	private

		def player_params
			params.require(:player).permit(:name)
		end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
		if signed_in?
			redirect_to board_games_path
		end
	end

	def create
		user = User.find_by(email: params[:session][:email].downcase)
		if user && user.authenticate(params[:session][:password])
			sign_in user
			redirect_to board_games_path
		else
			render 'new'
		end
	end

	def destroy
		sign_out
		redirect_to root_url
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  	def new
      if signed_in?
        redirect_to board_games_path
      else
        @user = User.new
      end
  	end

  	def create
  		user = User.new(user_params)
  		if user.save
        sign_in user
  			redirect_to board_games_path
  		else
  			render 'new'
  		end
  	end

  	private

  		def user_params
  			params.require(:user).permit(:name, :email,
  					 :password, :password_confirmation)
  		end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def full_title(title)
		base_title = "Board Games"
		if title.empty?
			base_title
		else
			"#{base_title} - #{title}"
		end
	end
end

app/helpers/board_games_helper.rb
module BoardGamesHelper
end

app/helpers/game_plays_helper.rb
module GamePlaysHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

	def sign_in(user)
		remember_token = User.new_remember_token
		cookies.permanent[:remember_token] = remember_token
		user.update_attribute(:remember_token, User.encrypt(remember_token))
		self.current_user = user
	end

	def signed_in?
		!current_user.nil?
	end

	def current_user=(user)
		@current_user = user
	end

	def current_user
		remember_token = User.encrypt(cookies[:remember_token])
		@current_user ||= User.find_by(remember_token: remember_token)
	end

	def sign_out
		current_user.update_attribute(:remember_token, User.encrypt(User.new_remember_token))
		cookies.delete(:remember_token)
		self.current_user = nil
	end

	def signed_in_user
		unless signed_in?
			redirect_to signin_path
		end
	end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/board_games/_board_game.html.haml
%li
	.block-grid-tile
		%a{ href: board_game_path(board_game.id) }
			%h5.text-center
				%strong
					= board_game.name
			%img.image-center.image-block-grid{ src: board_game.image_url }

app/views/board_games/edit.html.haml
%br
.row.text-center
	%h1
		%strong Edit Board Game

= form_for @board_game do |f|
	.row
		= render 'shared/error_messages', object: f.object
		.medium-8.large-6.columns.small-centered
			= f.text_field :name, placeholder: "Name"
		.medium-8.large-6.columns.small-centered
			= f.text_field :image_url, placeholder: "Image Url"
		.medium-8.large-6.columns.small-centered
			= f.text_field :starting_player_rule, placeholder: "Starting Player Rule"
		.medium-8.large-6.columns.small-centered
			= f.text_field :rule_book_link, placeholder: "Rule book link"
		.medium-8.large-6.columns.small-centered
			= f.label "Round based", for: :board_game_round_based, class: "label"
			= f.check_box :round_based
			= f.number_field :rounds, placeholder: "Rounds"
		.medium-8.large-6.columns.small-centered
			= f.text_area :description, placeholder: "Description"
		.medium-8.large-6.columns.small-centered
			= f.submit "Save changes", class: "button columns"

app/views/board_games/index.html.haml
.row
	- if @board_games.count > 0
		.block-grid
			%ul.small-block-grid-2.medium-block-grid-3.large-block-grid-4
				= render @board_games
	- else
		%a{ href: new_board_game_path }
			%h1 Add some games!

app/views/board_games/new.html.haml
.row
	%h1.text-center 
		%strong New board game

= form_for @board_game, url: { action: "create" } do |f|
	.row
		.medium-8.large-6.columns.small-centered
			= f.text_field :name, placeholder: "Name"
		.medium-8.large-6.columns.small-centered
			= f.text_field :image_url, placeholder: "Image Url"
		.medium-8.large-6.columns.small-centered
			= f.text_field :starting_player_rule, placeholder: "Starting Player Rule"
		.medium-8.large-6.columns.small-centered
			= f.text_field :rule_book_link, placeholder: "Rule book link"
		.medium-8.large-6.columns.small-centered
			= f.label "Round based", for: :board_game_round_based, class: "label"
			= f.check_box :round_based
			= f.number_field :rounds, placeholder: "Rounds"
		.medium-8.large-6.columns.small-centered
			= f.text_area :description, placeholder: "Description"
		.medium-8.large-6.columns.small-centered
			= f.submit "Create", class: "button small right"

app/views/board_games/show.html.haml
- provide(:title, @board_game.name)
%br
.row
	.medium-6.large-6.columns.right.text-center
		%h1 
			%strong 
				= @board_game.name
	.medium-6.large-6.columns.left
		%img.image-center{ src: @board_game.image_url }
		%br
	.medium-6.large-6.columns.right.text-center
		%a.button.large.columns{href: edit_board_game_path(@board_game.id) } Edit
		%a.button.large.columns.disabled Delete
.row
	.medium-6.large-6.columns.right
		- if !@board_game.starting_player_rule.blank?
			%h1 Starting Player
			%h4= @board_game.starting_player_rule
		- if !@board_game.rule_book_link.blank?
			%h1
				%a{href: @board_game.rule_book_link} Rulebook
		- if @board_game.round_based?
			%h1= "Rounds: #{@board_game.rounds}"
		- if !@board_game.description.blank?	
			%h1 Description
			%p= @board_game.description
	.medium-6.large-6.columns.text-center.left
		%h1= "Played: #{@board_game.game_plays.count}"
		- @board_game.game_plays.each do |gp|
			.board-game-game-play
				%h3= gp.date_string
				%h5= gp.players_string
				%br
	

app/views/game_plays/_game_play.html.haml
%li.show-for-small-only
	%a{href: game_play_path(game_play.id) }
		.game-play-item-small
			%h2
				%strong= game_play.board_game.name
			%h4= game_play.date_string
			%h5= game_play.player_count_string
			%p= game_play.players_string

%li.show-for-medium-up
	%a{href: game_play_path(game_play.id) }
		.game-play-item-medium
			.medium-4.large-4.columns
				%img.image-game-play-medium{src: game_play.board_game.image_url }
			.medium-8.large-8.columns
				%h1
					%strong= game_play.board_game.name
				%h3= game_play.date_string
				%h5= game_play.player_count_string
				%p= game_play.players_string

app/views/game_plays/index.html.haml
.row
	- if @game_plays.count > 0
		%ul.no-bullet
			= render @game_plays
	- else
		%h1 Go play some games!

app/views/game_plays/new.html.haml
.row
	%h1.text-center 
		%strong New Game Play

= form_for @game_play, url: { action: "create" } do |f|
	.row
		.medium-8.large-6.columns.small-centered
			= select_tag :board_game_id, options_from_collection_for_select(@board_games, :id, :name)
		.medium-8.large-6.columns.small-centered
			= f.collection_check_boxes(:player_ids, @players, :id, :name) do |b|
				- b.label(class: "game-play-label") { b.check_box(class: "game-play-checkbox") + " " + b.text }
		.medium-8.large-6.columns.small-centered
			= f.submit "Save", class: "button small right"

app/views/game_plays/show.html.haml
%br
.row
	.medium-6.large-6.columns.right.text-center
		%a{ href: board_game_path(@game_play.board_game.id) }
			%h1 
				%strong 
					= @game_play.board_game.name
		%h3= @game_play.date_string
	.medium-6.large-6.columns.left
		%img.image-center{ src: @game_play.board_game.image_url }
		%br
	.medium-6.large-6.columns.right.text-center
		%a.button.large.columns{href: edit_game_play_path(@game_play.id) } Edit
		= link_to 'Delete', game_play_path(@game_play.id),
			confirm: "Are you sure?", method: :delete, class: "button large columns"
.row
	.medium-6.large-6.columns.left
		%h1.text-center
			%strong= @game_play.player_count_string
		- @game_play.players.each do |p|
			%h2
				%a{href: player_path(p.id) }= p.name
				

app/views/layouts/_navbar.html.haml
- if signed_in?
	%head
		.contain-to-grid.fixed
			%nav.top-bar{ data: { "topbar" => true } }
				%ul.title-area
					%li.name
						%h1
							%a{ href: board_games_path } Board Games
					%li.toggle-topbar.menu-icon
						%a{ href: "#" }
							%span Menu
				%section.top-bar-section
					%ul.left
						%li.has-dropdown
							%a{ href: board_games_path } Board Games
							%ul.dropdown
								%li.show-for-small-only
									%a{href: board_games_path } All
								%li
									%a{href: new_board_game_path } New
						%li.has-dropdown
							%a{ href: game_plays_path } Game Plays
							%ul.dropdown
								%li.show-for-small-only
									%a{ href: game_plays_path } All
								%li
									%a{ href: new_game_play_path } New
						%li.has-dropdown
							%a{ href: players_path } Players
							%ul.dropdown
								%li.show-for-small-only
									%a{ href: players_path } All
								%li
									%a{ href: new_player_path } New
					%ul.right
						%li.has-dropdown
							%a{ href: "#" }= current_user.name
							%ul.dropdown
								%li
									%a{href: signout_path } Sign out

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= full_title(yield(:title)) %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <main role="main">
      <%= yield %>      
    </main>
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/players/_player.html.haml
%li
	.large-12.columns
		%h3
			%a{ href: player_path(player.id) }= player.name
			

app/views/players/index.html.haml
.row
	%ul.no-bullet
		= render @players

app/views/players/new.html.haml
.row
	%h1.text-center 
		%strong New Player

= form_for @player, url: { action: "create" } do |f|
	.row
		= render 'shared/error_messages', object: f.object
		.medium-8.large-6.columns.small-centered
			= f.text_field :name, placeholder: "Name"
		.medium-8.large-6.columns.small-centered
			= f.submit "Save", class: "button small right"

app/views/players/show.html.haml
%br
.row.text-center
	%h1 
		%strong 
			= @player.name
- if @player.game_plays.count > 0
	.row.text-center
		%h1= "Games Played: #{@player.game_plays.count}"
	.row
		= render @player.game_plays
- else
	.row.text-center
		%h1 No games yet :(

app/views/shared/_error_messages.html.haml
- if object.errors.any?
	- object.errors.full_messages.each do |msg|
		.alert-box.medium-8.large-6.columns.small-centered{ data: { alert => true } }
			= msg
			%a.close{href: "#" } &times;

app/views/users/new.html.haml
.row
	.medium-8.large-6.columns.small-centered
		%h1.text-center
			%strong Register
= form_for @user, url: register_path do |f|
	.row
		= render 'shared/error_messages', object: f.object
		.medium-8.large-6.columns.small-centered
			= f.text_field :name, placeholder: "Name"
		.medium-8.large-6.columns.small-centered
			= f.text_field :email, placeholder: "Email"
		.medium-8.large-6.columns.small-centered
			= f.password_field :password, placeholder: "Password"
		.medium-8.large-6.columns.small-centered
			= f.password_field :password_confirmation, placeholder: "Password Confirmation"
		.medium-8.large-6.columns.small-centered
			= f.submit "Register", class: "button small right"